### ISSUE TITLE
Ligatures not working.

### ISSUE THREAD

**Issue by Mohamed3on** [weirdpattern/hyper-ayu-light#2]
Simply, after enabling ligatures in CSS, they're not showing in this theme. Example:
![image](https://user-images.githubusercontent.com/12295159/28485853-c9d289ce-6e7c-11e7-84c9-d4cfa3484317.png)
With another theme:
![image](https://user-images.githubusercontent.com/12295159/28485954-aff68702-6e7d-11e7-9830-aa7f87f713b4.png)

**Comment by weirdpattern** [comment]
do you mind sharing the list of plugins you are loading?
Also, how are you enabling the ligatures?

**Comment by Mohamed3on** [comment]
`plugins: ['hypercwd', 'hyperlinks', 'hyperpower', 'hyperborder', 'hyperline']`
and ligatures are enabled with:
`  termCSS: ' x-screen x-row {  font-variant-ligatures: initial; }'`

**Comment by weirdpattern** [comment]
Thanks for the info. One more thing though... can I get the name of the other theme you are using?

**Comment by weirdpattern** [comment]
Ok, found the issue and is fixed now.
Thanks for reporting this issue, hope you are enjoying the theme
